---
upload_path: "/static/img/:year:/:month:/:day:"
frontmatter_file_url_template: "/static/:year:/:month:/:day:"
body_file_url_template: "/static/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  posts:
    default_front_matter_template: post
  photos:
    default_front_matter_template: photos
  microposts:
    default_front_matter_template: microposts
version: 0.38.1
