---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - technologie
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- name: aliases
  label: Aliases
  type: list
  hidden: false
  default: []
- name: toc
  label: Toc
  type: boolean
  hidden: false
  default: false
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: images
  label: Images
  type: list
  hidden: false
  default:
  - https://source.unsplash.com/category/technology/1600x900
